port = 8080
# port = 8443
https = false
cache_busting = true

[redirect]
port = 8081
enabled = false

[watch]
frontend = [
    "public",
    "frontend/Cargo.toml",
    "frontend/src",
    "../../crates/zoon/Cargo.toml",
    "../../crates/zoon/src",
    "../../crates/static_ref_macro/Cargo.toml",
    "../../crates/static_ref_macro/src",
]
backend = [
    "backend/Cargo.toml",
    "backend/src",
    "../../crates/moon/Cargo.toml",
    "../../crates/moon/src",
]
