[package]
version = "0.1.0"
name = "backend"
repository = "https://github.com/MartinKavik/MoonZoon"
authors = ["Martin Kav√≠k <martin@kavik.cz>"]
description = "Todos - MoonZoon example"
categories = ["MoonZoon", "example"]
license = "MIT"
readme = "../README.md"
edition = "2018"

[dependencies]
# moon = { git = "https://github.com/MartinKavik/MoonZoon" }
moon = { path = "../../../moon" }

[profile.release]
lto = true
codegen-units = 1
