[package]
version = "0.1.0"
name = "shared"
repository = "https://github.com/MoonZoon/MoonZoon"
authors = ["Martin Kav√≠k <martin@kavik.cz>"]
description = "Timer - MoonZoon example"
categories = ["MoonZoon", "example"]
license = "MIT"
readme = "../README.md"
edition = "2018"
