[workspace]

members = [
    "frontend",
    "backend",
]

[profile.release]
lto = true
codegen-units = 1

[profile.release.package.frontend]
opt-level = 's'

[profile.release.package.backend]
opt-level = 3
